[book]
authors = ["oluceps"]
language = "en"
multilingual = false
src = "doc"
title = "vaultix manual"

[output.html]
git-repository-url = "https://github.com/oluceps/vaultix"
git-repository-icon = "fa-github"
