on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
name: Clippy

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: |
          rustup default nightly
          rustup component add clippy
          cargo clippy --all-targets --all-features
