name: Docs

on:
  push:
    branches: ["*"]
    paths:
      - 'doc/*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

# Why don't you support yaml anchor?
jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-pr-review
          fail_on_error: true
      - name: Use custom config file
        uses: crate-ci/typos@master
      - uses: actions/checkout@v4
        with:
          repository: 'milieuim/mdbook-theme-milieuim'
          path: './theme'
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install mdBook
        run: |
          cargo install mdbook --no-default-features --features search --vers "^0.4" --locked
          cargo install mdbook-alerts --locked
      - name: Build mdBook
        run: |
          mdbook build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './book'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  build:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-pr-review
          fail_on_error: true
      - name: Use custom config file
        uses: crate-ci/typos@master
      - uses: actions/checkout@v4
        with:
          repository: 'myrrhlab/vaultix-mdbook-custom'
          path: './theme'
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install mdBook
        run: |
          cargo install mdbook --no-default-features --features search --vers "^0.4" --locked
          cargo install mdbook-alerts --locked
      - name: Build mdBook
        run: |
          mdbook build
