name: Evaluate
on:
  pull_request:
    branches: ["*"]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  push:
    branches: ["main", "dev"]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Build vaultix cli
        run: |
          nix build .

      - name: Run cargo check
        run: |
          nix develop -c cargo check

      - name: Run cargo test
        run: |
          nix develop -c cargo test
