name: Lint
on:
  pull_request:
    branches: ["*"]
    paths-ignore:
      - '**/*.md'
  push:
    branches: ["main", "dev"]
    paths-ignore:
      - '**/*.md'

permissions: read-all

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy:
    name: Clippy Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - name: Run cargo check
        run: nix develop -c cargo check
      - name: Run clippy
        run: nix develop -c cargo clippy --all-targets --all-features

