name: Evaluate Flake
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
jobs:
  check:
    name: format check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: flake check
        run: |
          nix flake check
        shell: bash

  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: build vaultix cli
        run: |
          nix build .#
        shell: bash
      - name: cargo check
        run: |
          nix develop -c cargo check
        shell: bash
